// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/signer.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/signer.proto

It has these top-level messages:
	SignRequest
	SignResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SignRequest struct {
	Key        []byte                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValidUntil *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	Message    string                     `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *SignRequest) Reset()                    { *m = SignRequest{} }
func (m *SignRequest) String() string            { return proto1.CompactTextString(m) }
func (*SignRequest) ProtoMessage()               {}
func (*SignRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SignRequest) GetValidUntil() *google_protobuf.Timestamp {
	if m != nil {
		return m.ValidUntil
	}
	return nil
}

func (m *SignRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignResponse struct {
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (m *SignResponse) Reset()                    { *m = SignResponse{} }
func (m *SignResponse) String() string            { return proto1.CompactTextString(m) }
func (*SignResponse) ProtoMessage()               {}
func (*SignResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignResponse) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func init() {
	proto1.RegisterType((*SignRequest)(nil), "proto.SignRequest")
	proto1.RegisterType((*SignResponse)(nil), "proto.SignResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Signer service

type SignerClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type signerClient struct {
	cc *grpc.ClientConn
}

func NewSignerClient(cc *grpc.ClientConn) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := grpc.Invoke(ctx, "/proto.Signer/Sign", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Signer service

type SignerServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
}

func RegisterSignerServer(s *grpc.Server, srv SignerServer) {
	s.RegisterService(&_Signer_serviceDesc, srv)
}

func _Signer_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Signer/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Signer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _Signer_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/signer.proto",
}

func init() { proto1.RegisterFile("proto/signer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4f, 0x84, 0x30,
	0x14, 0x84, 0xad, 0xbb, 0xae, 0xf1, 0xb1, 0x07, 0xf3, 0xbc, 0x34, 0x5c, 0x24, 0x3d, 0x71, 0x2a,
	0x11, 0x8f, 0xfc, 0x8b, 0xa2, 0x67, 0x03, 0xfa, 0x6c, 0x1a, 0xa1, 0x45, 0x5a, 0x48, 0xfc, 0xf7,
	0x86, 0x56, 0x12, 0xf7, 0xd4, 0x99, 0xc9, 0xe4, 0x9b, 0x3e, 0xc0, 0x69, 0x76, 0xc1, 0x55, 0xde,
	0x68, 0x4b, 0xb3, 0x8c, 0x06, 0x6f, 0xe2, 0x93, 0x3f, 0x6a, 0xe7, 0xf4, 0x40, 0x55, 0x74, 0xfd,
	0xf2, 0x59, 0x05, 0x33, 0x92, 0x0f, 0xdd, 0x38, 0xa5, 0x9e, 0x58, 0x21, 0x6b, 0x8d, 0xb6, 0x8a,
	0xbe, 0x17, 0xf2, 0x01, 0xef, 0xe1, 0xf0, 0x45, 0x3f, 0x9c, 0x15, 0xac, 0x3c, 0xab, 0x4d, 0x62,
	0x03, 0xd9, 0xda, 0x0d, 0xe6, 0xe3, 0x6d, 0xb1, 0xc1, 0x0c, 0xfc, 0xba, 0x60, 0x65, 0x56, 0xe7,
	0x32, 0x71, 0xe5, 0xce, 0x95, 0x2f, 0x3b, 0x57, 0x41, 0xac, 0xbf, 0x6e, 0x6d, 0xe4, 0x70, 0x3b,
	0x92, 0xf7, 0x9d, 0x26, 0x7e, 0x28, 0x58, 0x79, 0xa7, 0x76, 0x2b, 0x04, 0x9c, 0xd3, 0xae, 0x9f,
	0x9c, 0xf5, 0x84, 0x08, 0xc7, 0x77, 0x9a, 0xc3, 0xdf, 0x72, 0xd4, 0x75, 0x03, 0xa7, 0x36, 0xde,
	0x84, 0x4f, 0x70, 0xdc, 0x14, 0x62, 0x1a, 0x94, 0xff, 0xbe, 0x9c, 0x3f, 0x5c, 0x64, 0x09, 0x27,
	0xae, 0xfa, 0x53, 0x4c, 0x9f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xa3, 0xfe, 0x98, 0x1d,
	0x01, 0x00, 0x00,
}
